spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
        id.new_generator_mappings: false
  flyway:
    baseline-on-migrate: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pb_names
    username: postgres
    password: postgres

holidays:
  url: https://isdayoff.ru/

scheduledShuffles:
  weekend: '0 45 10 * * 1,2,4,5'
  wednesday: '0 45 10 * * 3'