name: "List_randomazer_CI"
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: pb_names
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    env:
      POSTGRES_DB: pb_names
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/pb_names"
    steps:
      - name: Install Java
        uses: actions/setup-java@v4.3.0
        with:
          java-version: 21
          distribution: 'adopt'
      - name: Set up database schema
        run: db:schema:load
      - name: Maven Package
        run: mvn -B clean package

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Install Java
        uses: actions/setup-java@v4.3.0
        with:
          java-version: 21
          distribution: 'adopt'
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.SSH_HOST}}
          user: ${{secrets.SSH_USER}}
          private_key: ${{secrets.SSH_PRIVATE_KEY}}
          command: |
            cd ${{ secrets.PROJECT_FOLDER }};
            sh stop.sh
            sh start.sh master DB_USERNAME=pb_names DB_PASSWORD=postgres DB_NAME=postgres DB_PORT=5555 APP_PORT=8099
