name: "List_randomazer_CI"
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: pb_names
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    env:
      POSTGRES_DB: pb_names
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/pb_names"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v4.3.0
        with:
          java-version: 21
          distribution: 'adopt'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Run tests
        run: ./gradlew test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v4.3.0
        with:
          java-version: 21
          distribution: 'adopt'
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@latest
        with:
          host: ${{secrets.SSH_HOST}}
          user: ${{secrets.SSH_USER}}
          private_key: ${{secrets.SSH_PRIVATE_KEY}}
          command: |
            cd ${{ secrets.PROJECT_FOLDER }};
            docker-compose --env-file ./.env stop
            gradle clean
            sleep 20
            git reset --hard
            git pull
            git checkout master
            echo "DB_USERNAME=pb_names" >> ./.env
            echo "DB_PASSWORD=postgres" >> ./.env
            echo "DB_NAME=postgres" >> ./.env
            echo "DB_PORT=5555" >> ./.env
            echo "APP_PORT=8099" >> ./.env
            docker-compose --env-file ./.env stop
            docker-compose --env-file ./.env up --build -d
